import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'

import { Toaster } from '@/components/ui/sonner'

import '@/styles/globals.css'

const font = Nunito({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${font.className} antialiased`}>
        {children}

        <Toaster richColors theme='light' />
      </body>
    </html>
  )
}
